#!/bin/bash
cd src/PandaController
mkdir build
cd build
cmake ..
make install
cd ../../..
catkin build relaxed_ik
catkin build panda_ros_msgs
catkin build panda_ros
#catkin_make --only-pkg-with-deps dmp_deformations -j12
catkin build inputs_ros
catkin build controller
