#!/bin/bash
cd src/PandaController
mkdir build
cd build
cmake ..
make install
cd ../../..
catkin_make --only-pkg-with-deps relaxed_ik
catkin_make --only-pkg-with-deps panda_ros
catkin_make --only-pkg-with-deps inputs_ros
