#!/usr/bin/env python
import rospy
from geometry_msgs.msg import TwistStamped
import numpy as np
import time

if __name__ == '__main__':
    rospy.init_node('panda_velocity_control_test')

    pub = rospy.Publisher('/panda/cart_velocity', TwistStamped, queue_size=1)

    angle = 0
    while True:
        msg = TwistStamped()
        msg.header.stamp = rospy.Time.now()
        msg.header.stamp.nsecs += 50000000
        msg.twist.linear.x = np.sin(angle)
        msg.twist.linear.y = np.sin(angle)
        msg.twist.linear.z = np.sin(angle)
        msg.twist.angular.x = np.cos(angle)
        msg.twist.angular.y = np.cos(angle)
        msg.twist.angular.z = np.cos(angle)
        pub.publish(msg)
        rospy.sleep(0.01)
        angle += 0.01